### ISSUE TITLE
Migrate business development and bounty system to Github

### ISSUE THREAD

**Issue by Seroxdesign** [Ricochet-Exchange/business-development#7]
# Bounty requirements

- Improving contribution guides
- Create ReadME for biz-dev repo 
- Migrate files from drive to Github
- Create issues in Github for bounties to be completed

**Comment by 0xSero** [comment]
Migration has been successful, all files moved, 
created issues om github for bounties
created readme for bounties
Improved contribution guides

**Comment by 0xSero** [comment]
![image](https://user-images.githubusercontent.com/69639595/167187191-7caf4d01-c4f1-408a-8f31-e0f6c1e14eb4.png)
![image](https://user-images.githubusercontent.com/69639595/167187245-198a6530-0d2f-434c-a645-2c9392914448.png)
![image](https://user-images.githubusercontent.com/69639595/167187401-b8366537-038e-4179-8d5d-c049162ff4d5.png)
![image](https://user-images.githubusercontent.com/69639595/167187508-81f0e31b-e8d6-4205-badc-2704583541b5.png)
