### ISSUE TITLE
Create and configure slack-social

### ISSUE THREAD

**Issue by 0xSero** [Ricochet-Exchange/business-development#9]
# Bounty requirements

- [ ] Reserve Ricochet Exchange name on all social media platforms (LinkedIn, Instagram, Reddit etc..)
- [ ] Create a slack social account and connect it to all our social medias
- [ ] Pay for the business version, configure features
- [ ] Write documentation so that Rexforce and begin posting to social media from one place
- [ ] Ensure account is secured and the correct permissions are provided

## Example of why this is a great asset:

- All members can participate without social credentials
- Automated batch posts and built in scheduling
- Built in analytics

![image](https://user-images.githubusercontent.com/69639595/166459465-27351dee-d0e2-487e-8027-25ff8da63272.png)

**Comment by mikeghen** [comment]
:+1:

**Comment by cryptochungus** [comment]
> # Bounty requirements
> * [X]  Reserve Ricochet Exchange name on all social media platforms (LinkedIn, Instagram, Reddit etc..)
> * [X]  Create a slack social account and connect it to all our social medias
> * [x]  Pay for the business version, configure features
> * [x]  Write documentation so that Rexforce and begin posting to social media from one place
> * [X]  Ensure account is secured and the correct permissions are provided
>

**Comment by 0xSero** [comment]
[Social Media Management.pdf](https://github.com/Ricochet-Exchange/business-development/files/8635835/Social.Media.Management.pdf)

Documentation

**Comment by mikeghen** [comment]
@Seroxdesign, can you get me access to Slack Social so I can verify this is done?
